fix(ci): add makepy and Conan

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,43 +1,116 @@
-default:
-  tags:
-    - ci
-  interruptible: true
+stages:
+  - lint
+  - main
+  - deploy
+  - deploy_tag
 
 variables:
-  GIT_STRATEGY: clone
-  ARTIFACTORY_API_KEY: $CICD_TOOLS_SC_ARTIFACTORY_API_KEY
-  BUILD_ID: gitlab_job_$CI_JOB_ID
-  BUILD_TYPE: Release
-  COMMON_BUILD_DIR: /home/ci_user/build
+  GIT_DEPTH: 5000
+  IMAGE: cpp_ubuntu_18
 
-main-job:
+workflow:
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+      when: never
+
+    - when: always
+
+default:
+  interruptible: true
+  tags:
+    - ci_shell
+  timeout: 6h
+  cache:
+    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
+    paths:
+      - .makepy/artifacts/cache/$CI_BUILDS_DIR/../.cache
+  before_script:
+    # SSH keys must have correct rights.
+    - chmod 600 "$MAKEPY_SSH"
+    # Register dynamically created ssh key in makepy credentials.
+    - cat "$MAKEPY_CREDS" | jq ".gitlab.ssh_path = \"$MAKEPY_SSH\"" | sponge "$MAKEPY_CREDS"
+    # Tell git about our dynamically created ssh key so it can download makepy from gitlab.
+    - export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i '$MAKEPY_SSH'"
+    # makepy tells conan about user and channel based on git branch. By default gitlab runs in 'detached HEAD' state,
+    # so we need to checkout to an actual branch.
+    - git checkout -B "$CI_COMMIT_BRANCH"
+    # Sometimes makepy fails to clean containers after the job. Clean them in before_script for such case.
+    - ./make.py container clean
+    # Create container with cache-mount-base local to this repo,
+    # eliminating its interference with other jobs and pipelines.
+    - ./make.py --image $IMAGE container run --cache-mount-base .makepy/artifacts/cache --credentials "$MAKEPY_CREDS"
+    # Install conan settings, profiles, remotes, toolchains and login to the registry.
+    - ./make.py --image $IMAGE conan-config --credentials "$MAKEPY_CREDS"
+    - CONAN_USER=$(./make.py --image $IMAGE --logging-level error conan-info user)
+    - CONAN_CHANNEL=$(./make.py --image $IMAGE --logging-level error conan-info channel)
+    - PACKAGE_NAME=$(./make.py --image $IMAGE --logging-level error conan-info package)
+    - BUILD_PATH=build/Release
+  after_script:
+    - echo "You can reproduce this pipeline with the following commands:"
+    - ./make.py history
+    - ./make.py container clean
+
+main:
+  stage: main
+  needs: []
+  parallel:
+    matrix:
+      - PROFILE: [default]
+        IMAGE: [cpp_ubuntu_18, cpp_centos_7]
+      - PROFILE: [makepy_sc_mingw]
+        IMAGE: [cpp_ubuntu_18]
   script:
-    - sudo chown -R ci_user .
-    - make container -f .ci/makefile
-    - make in_docker TARGET=build -f .ci/makefile
-    - exit_code=0
-    - make in_docker TARGET=test -f .ci/makefile || exit_code=$?
-    - |
-      if [[ "$exit_code" -ne 0 ]]; then
-        make in_docker TARGET=upload_test_report -f .ci/makefile
-        exit $exit_code
-      fi
-    - make in_docker TARGET=riscv-tests-debug -f .ci/makefile
-    - make in_docker TARGET=package -f .ci/makefile
-    - ./.ci/utils/upload_development_build.sh
-        $COMMON_BUILD_DIR/linux/install_openocd/linux_openocd.tar.gz
-    - ./.ci/utils/upload_development_build.sh
-        $COMMON_BUILD_DIR/windows/install_openocd/windows_openocd.zip
-    - BRANCH=$([ -z "$CI_COMMIT_TAG" ] && echo $CI_COMMIT_BRANCH || echo $CI_COMMIT_TAG)
-    - |
-      if [[ "$UPLOAD_STABLE_BUILDS" == "true" ]]; then
-        ./.ci/utils/check_nightly_status.sh "$ARTIFACTORY_API_KEY" || exit_code=$?
-        if [[ "$exit_code" -eq 0 ]]; then
-          # Upload release artifacts
-          ./.ci/utils/upload_artifact.sh $COMMON_BUILD_DIR/linux/install_openocd/linux_openocd.tar.gz $BRANCH
-          ./.ci/utils/upload_artifact.sh $COMMON_BUILD_DIR/windows/install_openocd/windows_openocd.zip $BRANCH
+    - ./make.py --image $IMAGE conan source .
+    - ./make.py --image $IMAGE conan install --profile:host $PROFILE .
+    - ./make.py --image $IMAGE config --build-path $BUILD_PATH
+    - ./make.py --image $IMAGE build --build-path $BUILD_PATH --target openocd
+    - if [[ "$PROFILE" == "makepy_sc_mingw" ]]; then exit; fi
+    - if [[ "$IMAGE" == "cpp_centos_7" ]]; then exit; fi # TODO: fix tests on CentOS
+    - ./make.py --image $IMAGE build --build-path $BUILD_PATH --target OpenOCDTest
+    - ./make.py --image $IMAGE build --build-path $BUILD_PATH --target RISCVTestsDebug
+
+deploy:
+  stage: deploy
+  needs: []
+  parallel:
+    matrix:
+      - PROFILE: [default]
+        IMAGE: [cpp_ubuntu_18, cpp_centos_7]
+      - PROFILE: [makepy_sc_mingw]
+        IMAGE: [cpp_ubuntu_18]
+  script:
+    - if git fetch origin "$PACKAGE_NAME" &> /dev/null; then
+        echo "[ERROR] Tag '$PACKAGE_NAME' already exists. Package will not be deployed!";
+        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
+          `# Silent exit on main branch`
+          exit;
         else
-          echo "could not find recods indicating that nightly passed"
-          echo "no artifacts for stable builds produced"
-        fi
+          `# Error exit on dev branches`
+          exit 1;
+        fi;
       fi
+    - if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
+        ./make.py --image $IMAGE ci check;
+      fi
+    - ./make.py --image $IMAGE conan create --profile:host $PROFILE --user $CONAN_USER --channel $CONAN_CHANNEL .
+    - ./make.py --image $IMAGE conan upload --remote syntacore --check "$PACKAGE_NAME"
+
+deploy_tag:
+  stage: deploy_tag
+  needs: [deploy]
+  script:
+    - git tag "$PACKAGE_NAME" --force
+    - git push "git@$CI_SERVER_HOST:$CI_PROJECT_PATH" "$PACKAGE_NAME"
+    - echo "Git Tag created successfully"
+
+
+lint:
+  stage: lint
+  needs: []
+  script:
+    - ./make.py --image $IMAGE format
+    - if [[ -n "$(git diff)" ]]; then git diff; exit 1; fi
+    - ./make.py --image $IMAGE lint
