fix 3
Change-Id: If85f59f88001780b615e5f33af501478bd3ad838
Signed-off-by: Jan Matyas <jmatyas@codasip.com>

diff --git a/.github/workflows/riscv-openocd-ci.yml b/.github/workflows/riscv-openocd-ci.yml
--- a/.github/workflows/riscv-openocd-ci.yml
+++ b/.github/workflows/riscv-openocd-ci.yml
@@ -34,14 +34,14 @@ jobs:
         run: bash tools/riscv-openocd-ci/run_tests.sh
 
       - name: Process test results
-        # If at least one test failed (or ended with an exception), this step fails: non-zero exit code.
+        # If at least one test failed (or ended with an exception), this step fails.
         run: |
           cd tools/riscv-openocd-ci
           python3 process_test_results.py --log-dir work/riscv-tests/debug/logs --output-dir work/results/logs
 
       - name: Store test results
         # Run even if there was a failed test
-        if: succeeded() || failed()
+        if: ${{ success() || failure() }}
         uses: actions/upload-artifact@v2
         with:
           name: test-results
@@ -49,14 +49,14 @@ jobs:
 
       - name: Collect OpenOCD code coverage
         # Run even if there was a failed test
-        if: succeeded() || failed()
+        if: ${{ success() || failure() }}
         run: |
           lcov --capture --directory . --output-file tools/riscv-openocd-ci/work/openocd-coverage.info
           genhtml tools/riscv-openocd-ci/work/openocd-coverage.info --output-directory tools/riscv-openocd-ci/work/results/openocd-coverage
 
       - name: Store OpenOCD code coverage
         # Run even if there was a failed test
-        if: succeeded() || failed()
+        if: ${{ success() || failure() }}
         uses: actions/upload-artifact@v2
         with:
           name: openocd-coverage
